version: '3.8'

services:
  rtmp-server:
    build:
      context: ./rtmp-server
    image: cdaprod/rtmp-server:latest
    container_name: rtmp_server
    network_mode: "host"
    volumes:
      - type: volume
        source: stream_recordings
        target: /data/recordings
    restart: always

  device-manager:
    build:
      context: ./device-manager
    image: cdaprod/device-manager:latest
    container_name: device_manager
    network_mode: "host"
    privileged: true
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - type: volume
        source: stream_recordings
        target: /data/recordings
    environment:
      - NAS_HOST=cda_ds.local
      - NAS_PATH=/volume1/videos
      - RTMP_SERVER=rtmp://127.0.0.1:1935/live
      - LOCAL_IP=192.168.0.187
      - OBS_WS_HOST=127.0.0.1
      - OBS_WS_PORT=4444
      - OBS_WS_PASSWORD=${OBS_WS_PASSWORD}
    depends_on:
      - rtmp-server
    restart: always

  api-router:
    build:
      context: ./api-router
    image: cdaprod/api-router:latest
    container_name: api_router
    network_mode: "host"
    environment:
      - DEVICE_MANAGER_URL=http://127.0.0.1:5000
      - RTMP_SERVER_URL=http://127.0.0.1:8080
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - rtmp-server
      - device-manager
    restart: always

  web-server:
    build:
      context: ./web-server
    image: cdaprod/web-server:latest
    container_name: web_server
    network_mode: "host"
    environment:
      - API_URL=http://localhost:8000
      - WS_URL=ws://localhost:8000/ws
    volumes:
      - ./web-server:/app
      - /app/node_modules
    depends_on:
      - api-router
    restart: always

volumes:
  stream_recordings:
    driver_opts:
      type: "nfs4"
      o: "addr=cda_ds.local,nolock,soft,rw"
      device: ":/volume1/videos"