services:
  # esp32_cam_streamer:
  #   build:
  #     context: ./ffmpeg-streamer
  #   image: cdaprod/ffmpeg-streamer:latest
  #   container_name: esp32_cam_streamer
  #   environment:
  #     - ESP32_CAM_URL=http://<esp32-cam-ip>/stream  # Replace with your ESP32-CAM IP
  #     - RTMP_SERVER_URL=rtmp://192.168.0.25:1935/live/esp_cam
  #   depends_on:
  #     - rtmp-server
  #   restart: always

  # Add more FFmpeg streamers if you have multiple ESP32-CAMs
  # esp32_cam_streamer_2:
  #   build:
  #     context: ./ffmpeg-streamer
  #   image: cdaprod/ffmpeg-streamer:latest
  #   container_name: esp32_cam_streamer_2
  #   environment:
  #     - ESP32_CAM_URL=http://<esp32-cam-ip-2>/stream
  #     - RTMP_SERVER_URL=rtmp://192.168.0.25:1935/live/esp_cam_2
  #   depends_on:
  #     - rtmp-server
  #   restart: always